remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: "AutoGluon: Leveraging Text, Images, and the Kitchen Sink to solve complex ML problems in a few lines of code with AutoGluon"
description: "PyData Seattle 2023, Microsoft Conference Center on Wednesday, April 26th at 9:00-10:30am, PDT in St. Helens."
